name: User Onboarding
description: Onboard users to repositories and organizations
title: "[Onboarding]: "
labels: ["onboarding"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to onboard users to repositories and organizations.
        
        After creating the issue, add a comment with the onboarding command:
        
        /onboard data/users.csv
        
        Ensure the CSV file exists in the repository with the correct format:
        mannequin-user,mannequin-id,target-user,role,target
        
        Where 'target' is either an organization name or 'owner/repo' for repositories.
        
        Permissions for repos: pull, push, admin
        Roles for orgs: admin, direct_member, billing_manager
  - type: input
    id: requester
    attributes:
      label: Requester
      description: Who is requesting this onboarding?
      placeholder: '@username'
    validations:
      required: true