name: User Onboarding Automation

on:
  issue_comment:
    types: [created]

env:
    ACTIONS_RUNNER_DEBUG: true

jobs:
  process_command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/onboard')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract CSV file name
      id: extract_csv
      run: |
        CSV_FILE=$(echo "${{ github.event.comment.body }}" | grep -oP '/onboard \K\S+')
        echo "csv_file=$CSV_FILE" >> $GITHUB_OUTPUT

    - name: Find CSV file
      id: find_csv
      run: |
        CSV_PATH=$(find ${{ github.workspace }} -name "${{ steps.extract_csv.outputs.csv_file }}" -print -quit)
        if [ -z "$CSV_PATH" ]; then
          echo "Error: CSV file not found in the repository"
          exit 1
        fi
        echo "csv_path=$CSV_PATH" >> $GITHUB_OUTPUT

    - name: Process mannequins
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        CSV_FILE: ${{ steps.find_csv.outputs.csv_path }}
      run: |
        python scripts/process_mannequins.py

    - name: Check for failures
      if: failure()
      run: |
        echo "One or more onboarding processes failed. Please check the logs for details."
        exit 1