name: User Onboarding Automation

on:
  issue_comment:
    types: [created]

jobs:
  process_command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/onboard')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract CSV file name
      id: extract_csv
      run: |
        CSV_FILE=$(echo "${{ github.event.comment.body }}" | grep -oP '/onboard \S+ \K\S+')
        echo "csv_file=$CSV_FILE" >> $GITHUB_OUTPUT

    - name: Process organization additions
      if: contains(github.event.comment.body, '/onboard orgs')
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        CSV_FILE: ${{ github.workspace }}/${{ steps.extract_csv.outputs.csv_file }}
        GITHUB_ORG: ${{ github.repository_owner }}
      run: |
        python scripts/add_to_orgs.py

    - name: Process repository additions
      if: contains(github.event.comment.body, '/onboard repos')
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        CSV_FILE: ${{ github.workspace }}/${{ steps.extract_csv.outputs.csv_file }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        python scripts/add_to_repos.py

    - name: Check for failures
      if: failure()
      run: |
        echo "One or more onboarding processes failed. Please check the logs for details."
        exit 1